function PREMPROCData (){

var PREMPROCarray =[
 {
   "License_Number": "CCL18-0003516",
   "Application_Number": "LCA18-0003516",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "No",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005192",
   "Application_Number": "LCA19-0005192",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004657",
   "Application_Number": "LCA19-0004657",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0003733",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001315",
   "Application_Number": "LCA19-0001315",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0001294",
   "Processing_Area": "Yes",
   "Packaging_Area": "No",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004012",
   "Application_Number": "LCA19-0004012",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA18-0003735",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0005173",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0000160",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "lca19-0000162",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0003069",
   "Processing_Area": "Yes",
   "Packaging_Area": "No",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004711",
   "Application_Number": "LCA19-0004711",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005240",
   "Application_Number": "LCA19-0005240",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005292",
   "Application_Number": "LCA19-0005292",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003702",
   "Application_Number": "LCA18-0003702",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005048",
   "Application_Number": "LCA19-0005048",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0000153",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "No",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0003185",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001190",
   "Application_Number": "LCA19-0001190",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0004772",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0003534",
   "Application_Number": "LCA19-0003534",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001154",
   "Application_Number": "LCA18-0001154",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001703",
   "Application_Number": "LCA18-0001703",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002664",
   "Application_Number": "LCA18-0002664",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005403",
   "Application_Number": "LCA19-0005403",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA18-0003785",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001341",
   "Application_Number": "LCA19-0001341",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005288",
   "Application_Number": "LCA19-0005288",
   "Processing_Area": "No",
   "Packaging_Area": "No",
   "Composting_Area": "No",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001672",
   "Application_Number": "LCA19-0001672",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005431",
   "Application_Number": "LCA19-0005431",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005317",
   "Application_Number": "LCA19-0005317",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002531",
   "Application_Number": "LCA19-0002531",
   "Processing_Area": "Yes",
   "Packaging_Area": "No",
   "Composting_Area": "No",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004999",
   "Application_Number": "LCA19-0004999",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002738",
   "Application_Number": "LCA18-0002738",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005100",
   "Application_Number": "LCA19-0005100",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003820",
   "Application_Number": "LCA18-0003820",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005191",
   "Application_Number": "LCA19-0005191",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005132",
   "Application_Number": "LCA19-0005132",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001074",
   "Application_Number": "LCA19-0001074",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005409",
   "Application_Number": "LCA19-0005409",
   "Processing_Area": "No",
   "Packaging_Area": "No",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001689",
   "Application_Number": "LCA18-0001689",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000194",
   "Application_Number": "lca19-0000194",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005350",
   "Application_Number": "LCA19-0005350",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": "Yes"
 },
 {
   "License_Number": "CCL19-0005567",
   "Application_Number": "LCA19-0005567",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005570",
   "Application_Number": "LCA19-0005570",
   "Processing_Area": "Yes",
   "Packaging_Area": "No",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004621",
   "Application_Number": "LCA19-0004621",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0000445",
   "Application_Number": "LCA18-0000445",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000064",
   "Application_Number": "LCA19-0000064",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002991",
   "Application_Number": "LCA18-0002991",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003034",
   "Application_Number": "LCA18-0003034",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002256",
   "Application_Number": "LCA18-0002256",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001422",
   "Application_Number": "LCA18-0001422",
   "Processing_Area": "Yes",
   "Packaging_Area": "No",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001919",
   "Application_Number": "LCA19-0001919",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000712",
   "Application_Number": "LCA19-0000712",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0000717",
   "Application_Number": "LCA18-0000717",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001544",
   "Application_Number": "LCA18-0001544",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": "Yes"
 },
 {
   "License_Number": "CCL18-0003514",
   "Application_Number": "LCA18-0003514",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002868",
   "Application_Number": "LCA19-0002868",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001348",
   "Application_Number": "LCA18-0001348",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002817",
   "Application_Number": "LCA18-0002817",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002660",
   "Application_Number": "LCA18-0002660",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003170",
   "Application_Number": "LCA18-0003170",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000316",
   "Application_Number": "LCA19-0000316",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0000223",
   "Application_Number": "LCA18-0000223",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003307",
   "Application_Number": "LCA18-0003307",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000589",
   "Application_Number": "LCA19-0000589",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "No",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005310",
   "Application_Number": "LCA19-0005310",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003219",
   "Application_Number": "LCA18-0003219",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001346",
   "Application_Number": "LCA18-0001346",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002194",
   "Application_Number": "LCA18-0002194",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000333",
   "Application_Number": "LCA19-0000333",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000696",
   "Application_Number": "LCA19-0000696",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002333",
   "Application_Number": "LCA19-0002333",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001641",
   "Application_Number": "LCA19-0001641",
   "Processing_Area": "Yes",
   "Packaging_Area": "No",
   "Composting_Area": "No",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "No",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0003373",
   "Application_Number": "LCA19-0003373",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001879",
   "Application_Number": "LCA19-0001879",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003436",
   "Application_Number": "LCA18-0003436",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003249",
   "Application_Number": "LCA18-0003249",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003482",
   "Application_Number": "LCA18-0003482",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001777",
   "Application_Number": "LCA18-0001777",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000676",
   "Application_Number": "LCA19-0000676",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003133",
   "Application_Number": "LCA18-0003133",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002100",
   "Application_Number": "LCA19-0002100",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000899",
   "Application_Number": "LCA19-0000899",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001790",
   "Application_Number": "LCA18-0001790",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003202",
   "Application_Number": "LCA18-0003202",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001731",
   "Application_Number": "LCA19-0001731",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0003785",
   "Application_Number": "LCA19-0003785",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001694",
   "Application_Number": "lca19-0001694",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "No",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "No",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002595",
   "Application_Number": "LCA18-0002595",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003712",
   "Application_Number": "LCA18-0003712",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001540",
   "Application_Number": "LCA19-0001540",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002347",
   "Application_Number": "LCA19-0002347",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003119",
   "Application_Number": "LCA18-0003119",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003564",
   "Application_Number": "LCA18-0003564",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001603",
   "Application_Number": "LCA19-0001603",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002279",
   "Application_Number": "LCA19-0002279",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003250",
   "Application_Number": "LCA18-0003250",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002207",
   "Application_Number": "LCA19-0002207",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "No",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001583",
   "Application_Number": "LCA18-0001583",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0003256",
   "Application_Number": "LCA19-0003256",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0003221",
   "Application_Number": "LCA18-0003221",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004719",
   "Application_Number": "LCA19-0004719",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000808",
   "Application_Number": "LCA19-0000808",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001095",
   "Application_Number": "LCA19-0001095",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002650",
   "Application_Number": "LCA18-0002650",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000972",
   "Application_Number": "LCA19-0000972",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002070",
   "Application_Number": "LCA19-0002070",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0001847",
   "Application_Number": "LCA19-0001847",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0002601",
   "Application_Number": "LCA19-0002601",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0003057",
   "Application_Number": "LCA19-0003057",
   "Processing_Area": "N/A",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "N/A",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0003141",
   "Application_Number": "LCA19-0003141",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004464",
   "Application_Number": "LCA19-0004464",
   "Processing_Area": "Yes",
   "Packaging_Area": "No",
   "Composting_Area": "No",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "No",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005092",
   "Application_Number": "LCA19-0005092",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000639",
   "Application_Number": "LCA19-0000639",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004576",
   "Application_Number": "LCA19-0004576",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0000327",
   "Application_Number": "LCA20-0000327",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0004913",
   "Application_Number": "LCA19-0004913",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0000467",
   "Application_Number": "LCA20-0000467",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0001393",
   "Application_Number": "LCA18-0001393",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0005619",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "No",
   "Harvest_Storage_Area": "No",
   "Designated shared area(s)": "No",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000976",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": "Yes"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000666",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": "Yes"
 },
 {
   "License_Number": "CCL19-0000461",
   "Application_Number": "LCA19-0000461",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": "Yes"
 },
 {
   "License_Number": "CCL19-0005452",
   "Application_Number": "LCA19-0005452",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0000287",
   "Application_Number": "LCA20-0000287",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0001586",
   "Application_Number": "LCA20-0001586",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": "Yes"
 },
 {
   "License_Number": "CCL20-0001837",
   "Application_Number": "LCA20-0001837",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": "Yes"
 },
 {
   "License_Number": "CCL19-0005197",
   "Application_Number": "LCA19-0005197",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": "Yes"
 },
 {
   "License_Number": "CCL20-0000431",
   "Application_Number": "LCA20-0000431",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0001306",
   "Application_Number": "LCA20-0001306",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0000385",
   "Application_Number": "LCA20-0000385",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": "N/A"
 },
 {
   "License_Number": "CCL19-0000236",
   "Application_Number": "LCA19-0000236",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005189",
   "Application_Number": "LCA19-0005189",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000936",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0000479",
   "Application_Number": "LCA20-0000479",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000329",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0001455",
   "Application_Number": "LCA20-0001455",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000755",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0001738",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0001073",
   "Application_Number": "LCA20-0001073",
   "Processing_Area": "yes",
   "Packaging_Area": "yes",
   "Composting_Area": "n/a",
   "Cannabis_Waste_Area": "yes",
   "Harvest_Storage_Area": "yes",
   "Designated shared area(s)": "n/a",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000816",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0005524",
   "Application_Number": "LCA19-0005524",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0000325",
   "Application_Number": "LCA20-0000325",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0001631",
   "Application_Number": "LCA20-0001631",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0000355",
   "Application_Number": "LCA20-0000355",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0000395",
   "Application_Number": "LCA18-0000395",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000017",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL20-0000177",
   "Application_Number": "LCA20-0000177",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000737",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0001587",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0001817",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0001862",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0002194",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0002238",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL18-0002802",
   "Application_Number": "LCA18-0002802",
   "Processing_Area": "Yes",
   "Packaging_Area": "No",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "N/A",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "CCL19-0000339",
   "Application_Number": "LCA19-0000339",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "Yes",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "Yes",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0002140",
   "Processing_Area": "Yes",
   "Packaging_Area": "N/A",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0002314",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0001859",
   "Processing_Area": "Yes",
   "Packaging_Area": "Yes",
   "Composting_Area": "N/A",
   "Cannabis_Waste_Area": "Yes",
   "Harvest_Storage_Area": "Yes",
   "Designated shared area(s)": "N/A",
   "Common Use Area(s)": ""
 }
];
 return PREMPROCarray;
}