function SMALLRETAILData (){

var SMALLRETAILarray =[
 {
   "License_Number": "",
   "Application_Number": "LCA18-0001488",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "N/A",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "N/A",
   "Name of retail supplier under the contract provided?": "N/A",
   "Coordinates of well provided?": "N/A",
   "Maximum amount of water delivered": "N/A",
   "Copy of well completion report": "N/A",
   "Copy of the most recent water service bill?": "N/A",
   "Currently Used for Cannabis": "",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL18-0002196",
   "Application_Number": "LCA18-0002196",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "",
   "Small Retail Water Suppliers": "Potter Valley Irrigation District"
 },
 {
   "License_Number": "CCL18-0002943",
   "Application_Number": "LCA18-0002943",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "",
   "Small Retail Water Suppliers": "Potter Valley Irrigation District"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0002301",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "",
   "Small Retail Water Suppliers": "Potter Valley Irrigation District"
 },
 {
   "License_Number": "CCL20-0001073",
   "Application_Number": "LCA20-0001073",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "",
   "Small Retail Water Suppliers": "Potter Valley Irrigation District"
 },
 {
   "License_Number": "CCL18-0000016",
   "Application_Number": "LCA18-0000016",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "",
   "Small Retail Water Suppliers": "Willow Creek Community Service District"
 },
 {
   "License_Number": "CCL18-0000017",
   "Application_Number": "LCA18-0000017",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "",
   "Small Retail Water Suppliers": "Willow Creek Community Service District"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA18-0001432",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA18-0002343",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL19-0002189",
   "Application_Number": "LCA19-0002189",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "N/A",
   "Name of retail supplier under the contract provided?": "N/A",
   "Coordinates of well provided?": "N/A",
   "Maximum amount of water delivered": "N/A",
   "Copy of well completion report": "N/A",
   "Copy of the most recent water service bill?": "N/A",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Potter Valley Irrigation District"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0000153",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0002954",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0002956",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA19-0002966",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL18-0002028",
   "Application_Number": "LCA18-0002028",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "No",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "HLM Water Delivery or Sanchez Garden Supply (uses"
 },
 {
   "License_Number": "CCL19-0004868",
   "Application_Number": "LCA19-0004868",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL19-0004757",
   "Application_Number": "LCA19-0004757",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Mendocino Water"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA18-0002781",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "No",
   "Copy of the most recent water service bill?": "No",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL19-0001328",
   "Application_Number": "LCA19-0001328",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "No",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "HLM"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA18-0000357",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "N/A",
   "Coordinates of well provided?": "N/A",
   "Maximum amount of water delivered": "N/A",
   "Copy of well completion report": "N/A",
   "Copy of the most recent water service bill?": "N/A",
   "Currently Used for Cannabis": "No",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "",
   "Application_Number": "LCA18-0000358",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "N/A",
   "Coordinates of well provided?": "N/A",
   "Maximum amount of water delivered": "N/A",
   "Copy of well completion report": "N/A",
   "Copy of the most recent water service bill?": "N/A",
   "Currently Used for Cannabis": "No",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL19-0005222",
   "Application_Number": "LCA19-0005222",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "N/A",
   "Coordinates of well provided?": "N/A",
   "Maximum amount of water delivered": "N/A",
   "Copy of well completion report": "N/A",
   "Copy of the most recent water service bill?": "N/A",
   "Currently Used for Cannabis": "No",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL18-0002948",
   "Application_Number": "LCA18-0002948",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "No",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "No",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "No",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "No",
   "Coordinates of well provided?": "No",
   "Maximum amount of water delivered": "No",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Fortner"
 },
 {
   "License_Number": "CCL18-0000490",
   "Application_Number": "LCA18-0000490",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "No",
   "Copy of most recent water service bill?": "No",
   "Or is the water source a well?": "N/A",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "No",
   "Small Retail Water Suppliers": "HLM Water Delivery"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA18-0001319",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "No",
   "Copy of most recent water service bill?": "No",
   "Or is the water source a well?": "N/A",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "No",
   "Small Retail Water Suppliers": "HLM Water Delivery"
 },
 {
   "License_Number": "CCL19-0000870",
   "Application_Number": "LCA19-0000870",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "No",
   "Copy of most recent water service bill?": "No",
   "Or is the water source a well?": "N/A",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "No",
   "Small Retail Water Suppliers": "HLM Water Delivery"
 },
 {
   "License_Number": "CCL18-0000459",
   "Application_Number": "LCA18-0000459",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Covelo Fire Department"
 },
 {
   "License_Number": "CCL18-0002313",
   "Application_Number": "LCA18-0002313",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL18-0002314",
   "Application_Number": "LCA18-0002314",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL19-0004889",
   "Application_Number": "LCA19-0004889",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": ""
 },
 {
   "License_Number": "CCL19-0003739",
   "Application_Number": "LCA19-0003739",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Surprise Valley Ranch"
 },
 {
   "License_Number": "CCL18-0002716",
   "Application_Number": "LCA18-0002716",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "N/A",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Bailey's Water"
 },
 {
   "License_Number": "CCL18-0002717",
   "Application_Number": "LCA18-0002717",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "N/A",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Bailey's Water"
 },
 {
   "License_Number": "CCL19-0002276",
   "Application_Number": "LCA19-0002276",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Rosco Transport"
 },
 {
   "License_Number": "CCL18-0003021",
   "Application_Number": "LCA18-0003021",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "No",
   "Copy of well completion report": "N/A",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Smith Property Restoration"
 },
 {
   "License_Number": "CCL19-0005285",
   "Application_Number": "LCA19-0005285",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "HLM"
 },
 {
   "License_Number": "CCL20-0000154",
   "Application_Number": "LCA20-0000154",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "Yes",
   "Name of Retail Water Supplier Provided?": "Yes",
   "Water source for diversion": "Yes",
   "Coordinates of any POD?": "Yes",
   "Authorized place of use": "Yes",
   "Maximum Amount of Water delivered to Applicant?": "Yes",
   "Copy of most recent water service bill?": "Yes",
   "Or is the water source a well?": "N/A",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "Potter Valley Irrigation District"
 },
 {
   "License_Number": "CCL20-0000805",
   "Application_Number": "LCA20-0000805",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "HLM"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000806",
   "Verified Small Retail Water Supplier": "",
   "Water Bill Address Matches Premises": "",
   "Is the water source a diversion?": "No",
   "Name of Retail Water Supplier Provided?": "N/A",
   "Water source for diversion": "N/A",
   "Coordinates of any POD?": "N/A",
   "Authorized place of use": "N/A",
   "Maximum Amount of Water delivered to Applicant?": "N/A",
   "Copy of most recent water service bill?": "N/A",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "HLM"
 },
 {
   "License_Number": "",
   "Application_Number": "LCA20-0000566",
   "Verified Small Retail Water Supplier": "Yes",
   "Water Bill Address Matches Premises": "Yes",
   "Is the water source a diversion?": "N/A",
   "Name of Retail Water Supplier Provided?": "",
   "Water source for diversion": "",
   "Coordinates of any POD?": "",
   "Authorized place of use": "",
   "Maximum Amount of Water delivered to Applicant?": "",
   "Copy of most recent water service bill?": "",
   "Or is the water source a well?": "Yes",
   "Name of retail supplier under the contract provided?": "Yes",
   "Coordinates of well provided?": "Yes",
   "Maximum amount of water delivered": "Yes",
   "Copy of well completion report": "Yes",
   "Copy of the most recent water service bill?": "Yes",
   "Currently Used for Cannabis": "Yes",
   "Small Retail Water Suppliers": "HLM Water Delivery"
 }
];
 return SMALLRETAILarray;
}