-- Detail
SELECT TOP 100  
[DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type] AS 'App Type', [DBO].[V_RECORD].[RECORD_ID] AS 'RECORD ID', [DBO].[V_RECORD].[DATE_OPENED] AS 'DATE OPENED', [DBO].[V_RECORD].[STATUS] AS 'STATUS'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE] WITH(NOLOCK)  ON [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE (([DBO].[V_RECORD].[RECORD_ID] LIKE ISNULL('TAL', '') + ISNULL('%','')) OR ([DBO].[V_RECORD].[RECORD_ID] LIKE ISNULL('TML', '') + ISNULL('%',''))) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type], [DBO].[V_RECORD].[RECORD_ID], [DBO].[V_RECORD].[DATE_OPENED], [DBO].[V_RECORD].[STATUS]
ORDER BY [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type] ASC;

-- CSS (none)