-- Detail
SELECT TOP 100  
[DBO].[V_PAYMENT].[RECORD_ID] AS 'RECORD ID', [DBO].[V_CASHIER_SESSION].[DATE_DEPOSIT] AS 'DATE DEPOSIT', [DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] AS 'DEPOSIT SLIP', [DBO].[V_CASHIER_SESSION].[SESSION_ID] AS 'SESSION ID', [DBO].[V_PAYMENT].[PAYMENT_METHOD] AS 'PAYMENT METHOD', [DBO].[V_PAYMENT].[TRANSACTION_TYPE] AS 'TRANSACTION TYPE'
FROM [DBO].[V_PAYMENT] WITH(NOLOCK) 
INNER JOIN [DBO].[V_CASHIER_SESSION] WITH(NOLOCK)  ON [DBO].[V_CASHIER_SESSION].[SESSION_ID]=[DBO].[V_PAYMENT].[SESSION_ID]
WHERE (([DBO].[V_PAYMENT].[RECORD_ID] = 'LCA-0000170')) AND (([DBO].[V_PAYMENT].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CASHIER_SESSION].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[V_PAYMENT].[RECORD_ID], [DBO].[V_CASHIER_SESSION].[DATE_DEPOSIT], [DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP], [DBO].[V_CASHIER_SESSION].[SESSION_ID], [DBO].[V_PAYMENT].[PAYMENT_METHOD], [DBO].[V_PAYMENT].[TRANSACTION_TYPE];

-- CSS (none)