-- Summary
SELECT TOP 100  
COUNT([DBO].[V_RECORD].[RECORD_ID]) AS 'Count(RECORD ID)'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
INNER JOIN [DBO].[V_CONDITION_RECORD] WITH(NOLOCK)  ON [DBO].[V_CONDITION_RECORD].[RECORD_ID]=[DBO].[V_RECORD].[RECORD_ID]
INNER JOIN [DBO].[V_CONTACT] WITH(NOLOCK)  ON [DBO].[V_CONTACT].[RECORD_ID]=[DBO].[V_RECORD].[RECORD_ID]
WHERE (([DBO].[V_CONDITION_RECORD].[CONDITION_NAME] = 'LiveScan Required') AND ([DBO].[V_CONDITION_RECORD].[STATUS] = 'Applied') AND ([DBO].[V_CONDITION_RECORD].[CONDITION_REC_STATUS] = 'A') AND ([DBO].[V_CONTACT].[CONTACT_TYPE] = 'Designated Responsible Party')) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CONDITION_RECORD].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CONTACT].[AGENCY_ID] = 'CALCANNABIS'));

-- Detail
SELECT TOP 10000  
[DBO].[V_RECORD].[RECORD_ID] AS 'Record Nbr', [DBO].[V_RECORD].[STATUS] AS 'Record Status', [DBO].[V_CONTACT].[NAME_FIRST] AS 'DRP First Name', [DBO].[V_CONTACT].[NAME_LAST] AS 'DRP Last Name', [DBO].[V_CONTACT].[EMAIL] AS 'DRP Email'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
INNER JOIN [DBO].[V_CONDITION_RECORD] WITH(NOLOCK)  ON [DBO].[V_CONDITION_RECORD].[RECORD_ID]=[DBO].[V_RECORD].[RECORD_ID]
INNER JOIN [DBO].[V_CONTACT] WITH(NOLOCK)  ON [DBO].[V_CONTACT].[RECORD_ID]=[DBO].[V_RECORD].[RECORD_ID]
WHERE (([DBO].[V_CONDITION_RECORD].[CONDITION_NAME] = 'LiveScan Required') AND ([DBO].[V_CONDITION_RECORD].[STATUS] = 'Applied') AND ([DBO].[V_CONDITION_RECORD].[CONDITION_REC_STATUS] = 'A') AND ([DBO].[V_CONTACT].[CONTACT_TYPE] = 'Designated Responsible Party')) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CONDITION_RECORD].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CONTACT].[AGENCY_ID] = 'CALCANNABIS'));

-- CSS (none)