-- Summary
SELECT TOP 100  
COUNT([DBO].[V_USER].[USER_ID]) AS 'Count(USER ID)'
FROM [DBO].[V_USER] WITH(NOLOCK) 
WHERE ( ([DBO].[V_USER].[PUBLIC_USER] = 'Y') ) AND (([DBO].[V_USER].[AGENCY_ID] = 'CALCANNABIS'));

-- Detail
SELECT TOP 100  
[DBO].[V_USER].[USER_ID] AS 'USER ID', [DBO].[V_USER].[EMAIL] AS 'EMAIL'
FROM [DBO].[V_USER] WITH(NOLOCK) 
WHERE ( ([DBO].[V_USER].[PUBLIC_USER] = 'Y') ) AND (([DBO].[V_USER].[AGENCY_ID] = 'CALCANNABIS'))
ORDER BY [DBO].[V_USER].[USER_ID] ASC;

-- CSS (none)