-- Summary
SELECT TOP 100  
[DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type] AS 'App Type', [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[License Type] AS 'License Type', COUNT([DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[License Type]) AS 'Count(License Type)'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE] WITH(NOLOCK)  ON [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
LEFT OUTER JOIN [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE] WITH(NOLOCK)  ON [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE ( ([DBO].[V_RECORD].[RECORD_ID] LIKE ISNULL(ISNULL('%', '') + ISNULL('TCA',''), '') + ISNULL('%','')) ) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type], [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[License Type];

-- Summary Totals
SELECT NULL AS 'App Type', NULL AS 'License Type', SUM([Count(License Type)]) AS 'Count(License Type)'
FROM (
SELECT TOP 100  
[DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type] AS 'App Type', [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[License Type] AS 'License Type', COUNT([DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[License Type]) AS 'Count(License Type)'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE] WITH(NOLOCK)  ON [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
LEFT OUTER JOIN [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE] WITH(NOLOCK)  ON [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE ( ([DBO].[V_RECORD].[RECORD_ID] LIKE ISNULL(ISNULL('%', '') + ISNULL('TCA',''), '') + ISNULL('%','')) ) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type], [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[License Type]
) AS q1 
;

-- Detail
SELECT TOP 100  
[DBO].[V_RECORD].[RECORD_ID] AS 'RECORD ID', [DBO].[V_RECORD].[DATE_OPENED] AS 'DATE OPENED', [DBO].[V_RECORD].[ACA_INITIATED] AS 'ACA INITIATED', [DBO].[V_RECORD].[STATUS] AS 'STATUS', [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type] AS 'App Type', [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[License Type] AS 'License Type'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE] WITH(NOLOCK)  ON [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
LEFT OUTER JOIN [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE] WITH(NOLOCK)  ON [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE ( ([DBO].[V_RECORD].[RECORD_ID] LIKE ISNULL(ISNULL('%', '') + ISNULL('TCA',''), '') + ISNULL('%','')) ) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[V_RECORD].[RECORD_ID], [DBO].[V_RECORD].[DATE_OPENED], [DBO].[V_RECORD].[ACA_INITIATED], [DBO].[V_RECORD].[STATUS], [DBO].[ASI::LIC_CC_TMP::APPLICATION TYPE].[App Type], [DBO].[ASI::LIC_CC_TMP::LICENSE TYPE].[License Type];

-- CSS (none)