-- Summary
SELECT TOP 100  
[DBO].[ASIT::LIC_REC::RECONCILIATION].[RC Number] AS 'RC Number',  sum( convert(numeric,[DBO].[ASIT::LIC_REC::RECONCILIATION].[Total Paid])) AS 'Total Paid'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::LIC_REC::RECONCILIATION] WITH(NOLOCK)  ON [DBO].[ASI::LIC_REC::RECONCILIATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
LEFT OUTER JOIN [DBO].[ASIT::LIC_REC::RECONCILIATION] WITH(NOLOCK)  ON [DBO].[ASIT::LIC_REC::RECONCILIATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE (([DBO].[V_RECORD].[RECORD_TYPE_SUBTYPE] = 'Reconciliation') AND ([DBO].[ASIT::LIC_REC::RECONCILIATION].[Date Paid] >= '08/01/2018') AND ([DBO].[ASIT::LIC_REC::RECONCILIATION].[Date Paid] <= '08/31/2018 11:59:59 PM')) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[ASIT::LIC_REC::RECONCILIATION].[RC Number];

-- Detail
SELECT TOP 100  
[DBO].[ASIT::LIC_REC::RECONCILIATION].[Payment Status] AS 'Payment Status', [DBO].[ASIT::LIC_REC::RECONCILIATION].[RC Number] AS 'RC #', [DBO].[ASIT::LIC_REC::RECONCILIATION].[RC Date] AS 'RC Date', [DBO].[V_RECORD].[RECORD_ID] AS 'Recon ID#', [DBO].[ASIT::LIC_REC::RECONCILIATION].[Record ID] AS 'Record ID #', [DBO].[ASIT::LIC_REC::RECONCILIATION].[Date Paid] AS 'Payment Date',  convert(numeric,[DBO].[ASIT::LIC_REC::RECONCILIATION].[Total Paid]) AS 'Total Paid', [DBO].[ASIT::LIC_REC::RECONCILIATION].[Method Type] AS 'Payment Method', [DBO].[ASIT::LIC_REC::RECONCILIATION].[Comments] AS 'Comments'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::LIC_REC::RECONCILIATION] WITH(NOLOCK)  ON [DBO].[ASI::LIC_REC::RECONCILIATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
LEFT OUTER JOIN [DBO].[ASIT::LIC_REC::RECONCILIATION] WITH(NOLOCK)  ON [DBO].[ASIT::LIC_REC::RECONCILIATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE (([DBO].[V_RECORD].[RECORD_TYPE_SUBTYPE] = 'Reconciliation') AND ([DBO].[ASIT::LIC_REC::RECONCILIATION].[Date Paid] >= '08/01/2018') AND ([DBO].[ASIT::LIC_REC::RECONCILIATION].[Date Paid] <= '08/31/2018 11:59:59 PM')) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
ORDER BY [DBO].[ASIT::LIC_REC::RECONCILIATION].[Payment Status] ASC, [DBO].[ASIT::LIC_REC::RECONCILIATION].[RC Number] ASC;

-- Detail Totals
SELECT NULL AS 'RC #', NULL AS 'RC Date', NULL AS 'Recon ID#', NULL AS 'Record ID #', NULL AS 'Payment Date', NULL AS 'Total Paid', NULL AS 'Payment Method', NULL AS 'Comments'
FROM (
SELECT TOP 100  
[DBO].[ASIT::LIC_REC::RECONCILIATION].[Payment Status] AS 'Payment Status', [DBO].[ASIT::LIC_REC::RECONCILIATION].[RC Number] AS 'RC #', [DBO].[ASIT::LIC_REC::RECONCILIATION].[RC Date] AS 'RC Date', [DBO].[V_RECORD].[RECORD_ID] AS 'Recon ID#', [DBO].[ASIT::LIC_REC::RECONCILIATION].[Record ID] AS 'Record ID #', [DBO].[ASIT::LIC_REC::RECONCILIATION].[Date Paid] AS 'Payment Date',  convert(numeric,[DBO].[ASIT::LIC_REC::RECONCILIATION].[Total Paid]) AS 'Total Paid', [DBO].[ASIT::LIC_REC::RECONCILIATION].[Method Type] AS 'Payment Method', [DBO].[ASIT::LIC_REC::RECONCILIATION].[Comments] AS 'Comments',[DBO].[ASIT::LIC_REC::RECONCILIATION].[Payment Status] as '__order1'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::LIC_REC::RECONCILIATION] WITH(NOLOCK)  ON [DBO].[ASI::LIC_REC::RECONCILIATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
LEFT OUTER JOIN [DBO].[ASIT::LIC_REC::RECONCILIATION] WITH(NOLOCK)  ON [DBO].[ASIT::LIC_REC::RECONCILIATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE (([DBO].[V_RECORD].[RECORD_TYPE_SUBTYPE] = 'Reconciliation') AND ([DBO].[ASIT::LIC_REC::RECONCILIATION].[Date Paid] >= '08/01/2018') AND ([DBO].[ASIT::LIC_REC::RECONCILIATION].[Date Paid] <= '08/31/2018 11:59:59 PM')) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
ORDER BY [DBO].[ASIT::LIC_REC::RECONCILIATION].[Payment Status] ASC, [DBO].[ASIT::LIC_REC::RECONCILIATION].[RC Number] ASC
) AS q1 
 GROUP BY [__order1]
ORDER BY [__order1];

-- CSS (none)