-- Summary
SELECT TOP 100  
[DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] AS 'DEPOSIT SLIP', SUM([DBO].[V_FEE_PAYMENT_HISTORY].[AMOUNT]) AS 'Sum(AMOUNT)'
FROM [DBO].[V_FEE_PAYMENT_HISTORY] WITH(NOLOCK) 
INNER JOIN [DBO].[V_CASHIER_SESSION] WITH(NOLOCK)  ON [DBO].[V_CASHIER_SESSION].[SESSION_ID]=[DBO].[V_FEE_PAYMENT_HISTORY].[SESSION_ID]
WHERE (([DBO].[V_FEE_PAYMENT_HISTORY].[UPDATED_DATE] BETWEEN '2016-03-01T00:00:00.000' AND '2018-04-30T23:59:59.000')) AND (([DBO].[V_FEE_PAYMENT_HISTORY].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CASHIER_SESSION].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP];

-- Summary Totals
SELECT NULL AS 'DEPOSIT SLIP', SUM([Sum(AMOUNT)]) AS 'Sum(AMOUNT)'
FROM (
SELECT TOP 100  
[DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] AS 'DEPOSIT SLIP', SUM([DBO].[V_FEE_PAYMENT_HISTORY].[AMOUNT]) AS 'Sum(AMOUNT)'
FROM [DBO].[V_FEE_PAYMENT_HISTORY] WITH(NOLOCK) 
INNER JOIN [DBO].[V_CASHIER_SESSION] WITH(NOLOCK)  ON [DBO].[V_CASHIER_SESSION].[SESSION_ID]=[DBO].[V_FEE_PAYMENT_HISTORY].[SESSION_ID]
WHERE (([DBO].[V_FEE_PAYMENT_HISTORY].[UPDATED_DATE] BETWEEN '2016-03-01T00:00:00.000' AND '2018-04-30T23:59:59.000')) AND (([DBO].[V_FEE_PAYMENT_HISTORY].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CASHIER_SESSION].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP]
) AS q1 
;

-- Detail
SELECT TOP 1000  
[DBO].[V_FEE_PAYMENT_HISTORY].[ACTION] AS 'ACTION', [DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] AS 'DEPOSIT SLIP', [DBO].[V_FEE_PAYMENT_HISTORY].[SESSION_ID] AS 'SESSION ID', [DBO].[V_FEE_PAYMENT_HISTORY].[CASHIER_USERID] AS 'CASHIER USERID', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYMENT_ID] AS 'PAYMENT ID', [DBO].[V_FEE_PAYMENT_HISTORY].[RECORD_ID] AS 'RECORD ID', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYOR] AS 'PAYOR', [DBO].[V_FEE_PAYMENT_HISTORY].[DATE_PAYMENT] AS 'DATE PAYMENT', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYMENT_METHOD] AS 'PAYMENT METHOD', [DBO].[V_FEE_PAYMENT_HISTORY].[AMOUNT] AS 'AMOUNT', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYMENT_REFERENCE] AS 'PAYMENT REFERENCE', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYMENT_COMMENTS] AS 'PAYMENT COMMENTS'
FROM [DBO].[V_FEE_PAYMENT_HISTORY] WITH(NOLOCK) 
INNER JOIN [DBO].[V_CASHIER_SESSION] WITH(NOLOCK)  ON [DBO].[V_CASHIER_SESSION].[SESSION_ID]=[DBO].[V_FEE_PAYMENT_HISTORY].[SESSION_ID]
WHERE (([DBO].[V_FEE_PAYMENT_HISTORY].[UPDATED_DATE] BETWEEN '2016-03-01T00:00:00.000' AND '2018-04-30T23:59:59.000')) AND (([DBO].[V_FEE_PAYMENT_HISTORY].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CASHIER_SESSION].[AGENCY_ID] = 'CALCANNABIS'))
ORDER BY [DBO].[V_FEE_PAYMENT_HISTORY].[ACTION] ASC, [DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] ASC, [DBO].[V_FEE_PAYMENT_HISTORY].[DATE_PAYMENT] ASC;

-- Detail Totals
SELECT NULL AS 'DEPOSIT SLIP', NULL AS 'SESSION ID', NULL AS 'CASHIER USERID', NULL AS 'PAYMENT ID', NULL AS 'RECORD ID', NULL AS 'PAYOR', NULL AS 'DATE PAYMENT', NULL AS 'PAYMENT METHOD', SUM([AMOUNT]) AS 'AMOUNT', NULL AS 'PAYMENT REFERENCE', NULL AS 'PAYMENT COMMENTS'
FROM (
SELECT TOP 1000  
[DBO].[V_FEE_PAYMENT_HISTORY].[ACTION] AS 'ACTION', [DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] AS 'DEPOSIT SLIP', [DBO].[V_FEE_PAYMENT_HISTORY].[SESSION_ID] AS 'SESSION ID', [DBO].[V_FEE_PAYMENT_HISTORY].[CASHIER_USERID] AS 'CASHIER USERID', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYMENT_ID] AS 'PAYMENT ID', [DBO].[V_FEE_PAYMENT_HISTORY].[RECORD_ID] AS 'RECORD ID', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYOR] AS 'PAYOR', [DBO].[V_FEE_PAYMENT_HISTORY].[DATE_PAYMENT] AS 'DATE PAYMENT', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYMENT_METHOD] AS 'PAYMENT METHOD', [DBO].[V_FEE_PAYMENT_HISTORY].[AMOUNT] AS 'AMOUNT', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYMENT_REFERENCE] AS 'PAYMENT REFERENCE', [DBO].[V_FEE_PAYMENT_HISTORY].[PAYMENT_COMMENTS] AS 'PAYMENT COMMENTS',[DBO].[V_FEE_PAYMENT_HISTORY].[ACTION] as '__order1'
FROM [DBO].[V_FEE_PAYMENT_HISTORY] WITH(NOLOCK) 
INNER JOIN [DBO].[V_CASHIER_SESSION] WITH(NOLOCK)  ON [DBO].[V_CASHIER_SESSION].[SESSION_ID]=[DBO].[V_FEE_PAYMENT_HISTORY].[SESSION_ID]
WHERE (([DBO].[V_FEE_PAYMENT_HISTORY].[UPDATED_DATE] BETWEEN '2016-03-01T00:00:00.000' AND '2018-04-30T23:59:59.000')) AND (([DBO].[V_FEE_PAYMENT_HISTORY].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CASHIER_SESSION].[AGENCY_ID] = 'CALCANNABIS'))
ORDER BY [DBO].[V_FEE_PAYMENT_HISTORY].[ACTION] ASC, [DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] ASC, [DBO].[V_FEE_PAYMENT_HISTORY].[DATE_PAYMENT] ASC
) AS q1 
 GROUP BY [__order1]
ORDER BY [__order1];

-- CSS (none)
-- Landscape printing, page number, date and time