-- Detail
SELECT TOP 100  
[DBO].[V_RECORD].[RECORD_ID] AS 'Annual Application Number', [DBO].[V_RECORD].[RECORD_STATUS] AS 'Annual Application Status', [DBO].[ASI::LIC_CC_LIC::LICENSE TYPE].[Temp App Number] AS 'Temporary Record Number', [DBO].[V_RELATED_RECORD].[CHILD_STATUS] AS 'Temporary Record Status'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
INNER JOIN [DBO].[V_RELATED_RECORD] WITH(NOLOCK)  ON [DBO].[V_RELATED_RECORD].[PARENT_RECORD_ID]=[DBO].[V_RECORD].[RECORD_ID]
LEFT OUTER JOIN [DBO].[ASI::LIC_CC_LIC::LICENSE TYPE] WITH(NOLOCK)  ON [DBO].[ASI::LIC_CC_LIC::LICENSE TYPE].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE (([DBO].[V_RECORD].[RECORD_STATUS] LIKE ISNULL(ISNULL('%', '') + ISNULL('Denied',''), '') + ISNULL('%','')) AND (NOT([DBO].[ASI::LIC_CC_LIC::LICENSE TYPE].[Temp App Number] IS NULL)) AND ([DBO].[V_RELATED_RECORD].[CHILD_TYPE_SUBTYPE] = 'Temporary')) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_RELATED_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
ORDER BY [DBO].[V_RECORD].[RECORD_ID] ASC;

-- CSS (none)