-- Summary
SELECT TOP 100  
[DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type] AS 'Case Type', COUNT([DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type]) AS 'Count(Case Type)'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION] WITH(NOLOCK)  ON [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE ( ([DBO].[V_RECORD].[RECORD_TYPE_GROUP] = 'Enforcement') ) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type];

-- Summary Totals
SELECT NULL AS 'Case Type', SUM([Count(Case Type)]) AS 'Count(Case Type)'
FROM (
SELECT TOP 100  
[DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type] AS 'Case Type', COUNT([DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type]) AS 'Count(Case Type)'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION] WITH(NOLOCK)  ON [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE ( ([DBO].[V_RECORD].[RECORD_TYPE_GROUP] = 'Enforcement') ) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type]
) AS q1 
;

-- Detail
SELECT TOP 100  
[DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type] AS 'Case Type', [DBO].[V_RECORD].[RECORD_ID] AS 'Case ID', [DBO].[V_RECORD].[STATUS] AS 'Case Status', [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Due Date] AS 'Due Date', [DBO].[V_RECORD].[ASSIGNED_USERID] AS 'Assigned To'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
LEFT OUTER JOIN [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION] WITH(NOLOCK)  ON [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE ( ([DBO].[V_RECORD].[RECORD_TYPE_GROUP] = 'Enforcement') ) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS'))
ORDER BY [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type] ASC, [DBO].[V_RECORD].[STATUS] ASC;

-- CSS (none)