-- Summary
SELECT TOP 100  
[DBO].[V_WORKFLOW].[ASSIGNED_NAME_FML#] AS 'ASSIGNED NAME FML#', COUNT([DBO].[V_WORKFLOW].[ACTION_BY_NAME_FML#]) AS 'Count(ACTION BY NAME FML#)'
FROM [DBO].[V_WORKFLOW] WITH(NOLOCK) 
WHERE ( ([DBO].[V_WORKFLOW].[TASK] = 'Administrative Review') AND ([DBO].[V_WORKFLOW].[RECORD_STATUS] = 'Submitted') ) AND (([DBO].[V_WORKFLOW].[AGENCY_ID] = 'CALCANNABIS'))
GROUP BY [DBO].[V_WORKFLOW].[ASSIGNED_NAME_FML#]
ORDER BY COUNT([DBO].[V_WORKFLOW].[ACTION_BY_NAME_FML#]) ASC;

-- Detail
SELECT TOP 100  
[DBO].[V_WORKFLOW].[RECORD_ID] AS 'RECORD ID', [DBO].[V_WORKFLOW].[RECORD_STATUS] AS 'RECORD STATUS', [DBO].[V_WORKFLOW].[ASSIGNED_NAME_FML#] AS 'ASSIGNED NAME FML#', [DBO].[V_WORKFLOW].[DATE_ASSIGNED] AS 'DATE ASSIGNED'
FROM [DBO].[V_WORKFLOW] WITH(NOLOCK) 
WHERE ( ([DBO].[V_WORKFLOW].[TASK] = 'Administrative Review') AND ([DBO].[V_WORKFLOW].[RECORD_STATUS] = 'Submitted') ) AND (([DBO].[V_WORKFLOW].[AGENCY_ID] = 'CALCANNABIS'));

-- CSS (none)