-- Detail
SELECT TOP 10000  
[DBO].[V_RECORD].[ASSIGNED_USERID] AS 'Investigator', [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type] AS 'Case Type', [DBO].[V_RECORD].[RECORD_ID] AS 'Case Number', [DBO].[V_RECORD].[DATE_OPENED] AS 'Submit Date', [DBO].[V_RECORD].[RECORD_STATUS] AS 'Case Status', [DBO].[V_RECORD].[DATE_ASSIGNED] AS 'Assigned Date', [DBO].[V_RECORD].[DESCRIPTION] AS 'Case Description', [DBO].[V_RELATED_RECORD].[PARENT_RECORD_ID] AS 'License', [DBO].[V_CONTACT].[NAME_MIDDLE] AS 'Business'
FROM [DBO].[V_RECORD] WITH(NOLOCK) 
INNER JOIN [DBO].[V_RELATED_RECORD] WITH(NOLOCK)  ON [DBO].[V_RELATED_RECORD].[CHILD_RECORD_ID]=[DBO].[V_RECORD].[RECORD_ID]
INNER JOIN [DBO].[V_CONTACT] WITH(NOLOCK)  ON [DBO].[V_CONTACT].[RECORD_ID]=[DBO].[V_RELATED_RECORD].[PARENT_RECORD_ID]
LEFT OUTER JOIN [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION] WITH(NOLOCK)  ON [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[ID]=[DBO].[V_RECORD].[TEMPLATE_ID]
WHERE (([DBO].[V_RECORD].[RECORD_TYPE_GROUP] = 'Enforcement') AND ([DBO].[V_CONTACT].[CONTACT_TYPE] = 'Business') AND (NOT([DBO].[V_RECORD].[RECORD_STATUS] = 'All'))) AND (([DBO].[V_RECORD].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_RELATED_RECORD].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_CONTACT].[AGENCY_ID] = 'CALCANNABIS'))
ORDER BY [DBO].[V_RECORD].[ASSIGNED_USERID] ASC, [DBO].[ASI::ENF_COMPLNT::COMPLAINT INFORMATION].[Case Type] ASC, [DBO].[V_RECORD].[RECORD_STATUS] ASC;

-- CSS (none)
-- Landscape printing