-- Detail
SELECT TOP 100  
[DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] AS 'DEPOSIT SLIP', [DBO].[V_PAYMENT].[RECORD_ID] AS 'RECORD ID', [DBO].[V_PAYMENT].[DATE_PAYMENT] AS 'DATE PAYMENT', [DBO].[V_PAYMENT].[PAYMENT_METHOD] AS 'PAYMENT METHOD', [DBO].[V_PAYMENT].[AMOUNT] AS 'AMOUNT', [DBO].[V_PAYMENT].[PAYMENT_REFERENCE] AS 'PAYMENT REFERENCE'
FROM [DBO].[V_CASHIER_SESSION] WITH(NOLOCK) 
INNER JOIN [DBO].[V_PAYMENT] WITH(NOLOCK)  ON [DBO].[V_PAYMENT].[SESSION_ID]=[DBO].[V_CASHIER_SESSION].[SESSION_ID]
WHERE (([DBO].[V_CASHIER_SESSION].[DEPOSIT_SLIP] = 'RC-001')) AND (([DBO].[V_CASHIER_SESSION].[AGENCY_ID] = 'CALCANNABIS')) AND (([DBO].[V_PAYMENT].[AGENCY_ID] = 'CALCANNABIS'));

-- CSS (none)